language: swift
osx_image: xcode9.4
script:
    - xcodebuild -workspace ios-mvvm-pattern-example.xcworkspace -scheme ios-mvvm-pattern-exampleTests -sdk iphonesimulator -destination platform="iOS Simulator,name=iPhone 8,OS=11.4" test